# This workflow fetches the V4 Version of the Joomla CMS and syncs the needed source language files
# into the core-translations repository. After this it creates a new commit

name: J4 Get Core Source Language files

on:
  # Runs once a day at 6:12
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

jobs:
  synchronize-with-crowdin:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v3

    # Runs the Crowdin action command - https://github.com/crowdin/github-action
    - name: crowdin action package files
      uses: crowdin/github-action@1.4.8
      with:
        # Upload sources to Crowdin
        upload_sources: true
        # Option to specify a path to the configuration file, without / at the beginning
        config: 'Configurations/Crowdin-J4-All.yml'
        # Use true for dryrun to test the run without actually processing anything
        debug_mode: true
